import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!

        </h1>

        <p className={styles.description}>
          <code className={styles.code}>{"Hi I'm Faye!"}</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About Me&rarr;</h2>
            <p>My experience</p>
          </a>

          <a href="https://www.youtube.com/watch?v=TsHyTniI2U0" className={styles.card}>
            <h2>Resume &rarr;</h2>
            <p>My resume and associated documents</p>
          </a>

          <a
            href="https://github.com/fayesajid"
            className={styles.card}
          >
            <h2>My Github &rarr;</h2>
            <p>My past work</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>In progress &rarr;</h2>
            <p>
              Plans for the future and my future projects!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {'Thank you for visiting!'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={50} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
